import type { Language } from "./types";

const values: Record<Language, Record<string, string>> = {
  mk: {
    SME: "МСП",
    MidCap: "Mid-cap",
    PublicInstitution: "Јавна институција",
    Partner: "Партнер",
    Other: "Друго",
    DIGITAL_BUSINESS_STRATEGY: "Дигитална деловна стратегија",
    DIGITAL_READINESS: "Дигитална подготвеност",
    HUMAN_CENTRIC_DIGITALISATION: "Дигитализација насочена кон луѓето",
    DATA_MANAGEMENT: "Управување со податоци",
    GREEN_DIGITALISATION: "Зелена дигитализација",
    AI_READINESS: "AI подготвеност",
    AI_ACT_COMPLIANCE: "AI Act и усогласеност",
    AI_USE_CASE: "AI use-case",
    AUTOMATION_AND_INTELLIGENCE: "Автоматизација и интелигенција",
    TEST_BEFORE_INVEST: "Тестирај пред инвестиција",
    DIGITALIZATION_ROADMAP: "Патоказ за дигитализација",
    DATA_GOVERNANCE: "Управување со податоци",
    TRAINING_SKILLS: "Обуки и вештини",
    TRAINING_AND_SKILLS: "Обуки и вештини",
    FUNDING_SUPPORT: "Поддршка за финансирање",
    FUNDING_AND_INVESTMENT: "Финансирање и инвестиции",
    REFERRAL: "Упатување",
    OTHER: "Друго",
    Low: "Низок",
    Normal: "Нормален",
    High: "Висок",
    Urgent: "Итен",
    New: "Нов",
    Responded: "Одговорено",
    Handled: "Обработено",
    RegistrationInvited: "Поканет за регистрација",
    Triage: "За преглед",
    Assigned: "Доделен",
    InProgress: "Во работа",
    WaitingForClient: "Се чека клиент",
    WaitingForExpert: "Се чека експерт",
    Resolved: "Решен",
    Closed: "Затворен",
    Invited: "Поканет",
    Accepted: "Активна",
    PendingPayment: "Се чека уплата",
    PendingVerification: "Чека потврда на е-пошта",
    Active: "Активна",
    Inactive: "Неактивна",
    Expired: "Истечена",
    Cancelled: "Откажана",
    Requested: "Побаран",
    Confirmed: "Потврден",
    Rejected: "Одбиен",
    Completed: "Завршен",
    Online: "Онлајн",
    Offline: "Во живо",
    Hybrid: "Хибриден",
    Consultation: "Консултација",
    TechnicalReview: "Технички преглед",
    FollowUp: "Следен состанок",
    PendingApproval: "Чека одобрување",
    Approved: "Одобрена",
    Suspended: "Суспендирана",
    SystemEvent: "Системски настан",
    InternalNote: "Внатрешна белешка",
    ClientMessage: "Порака од клиент",
    StaffReply: "Одговор од поддршка",
    Client: "Клиент",
    HelpDeskAgent: "Help-desk советник",
    Expert: "Експерт",
    Admin: "Администратор",
    Ticket: "Тикет",
    Meeting: "Состанок",
    Subscription: "Претплата",
    ContactRequest: "Контакт барање",
    KpiPeriod: "KPI период",
    Published: "Објавено",
    Draft: "Нацрт",
    Archived: "Архивирано",
    organizationType: "тип на организација",
    sector: "сектор",
    region: "регион",
    need: "потреба",
    dmaCategory: "DMA категорија",
    status: "статус",
    assignee: "доделено лице",
    category: "категорија",
    type: "тип",
    recommendation: "препорака",
    tickets: "тикети",
    contacts: "контакти",
    meetings: "состаноци",
    subscriptions: "претплати",
  },
  en: {
    SME: "SME",
    MidCap: "Mid-cap",
    PublicInstitution: "Public institution",
    Partner: "Partner",
    Other: "Other",
    DIGITAL_BUSINESS_STRATEGY: "Digital business strategy",
    DIGITAL_READINESS: "Digital readiness",
    HUMAN_CENTRIC_DIGITALISATION: "Human-centric digitalisation",
    DATA_MANAGEMENT: "Data management",
    GREEN_DIGITALISATION: "Green digitalisation",
    AI_READINESS: "AI readiness",
    AI_ACT_COMPLIANCE: "AI Act & compliance",
    AI_USE_CASE: "AI use case",
    AUTOMATION_AND_INTELLIGENCE: "Automation & intelligence",
    TEST_BEFORE_INVEST: "Test before invest",
    DIGITALIZATION_ROADMAP: "Digitalisation roadmap",
    DATA_GOVERNANCE: "Data governance",
    TRAINING_SKILLS: "Training & skills",
    TRAINING_AND_SKILLS: "Training & skills",
    FUNDING_SUPPORT: "Funding support",
    FUNDING_AND_INVESTMENT: "Funding & investment",
    REFERRAL: "Referral",
    OTHER: "Other",
    Low: "Low",
    Normal: "Normal",
    High: "High",
    Urgent: "Urgent",
    New: "New",
    Responded: "Responded",
    Handled: "Handled",
    RegistrationInvited: "Invited to register",
    Triage: "For review",
    Assigned: "Assigned",
    InProgress: "In progress",
    WaitingForClient: "Waiting for client",
    WaitingForExpert: "Waiting for expert",
    Resolved: "Resolved",
    Closed: "Closed",
    Invited: "Invited",
    Accepted: "Active",
    PendingPayment: "Pending payment",
    PendingVerification: "Pending email verification",
    Active: "Active",
    Inactive: "Inactive",
    Expired: "Expired",
    Cancelled: "Cancelled",
    Requested: "Requested",
    Confirmed: "Confirmed",
    Rejected: "Rejected",
    Completed: "Completed",
    Online: "Online",
    Offline: "In person",
    Hybrid: "Hybrid",
    Consultation: "Consultation",
    TechnicalReview: "Technical review",
    FollowUp: "Follow-up",
    PendingApproval: "Pending approval",
    Approved: "Approved",
    Suspended: "Suspended",
    SystemEvent: "System event",
    InternalNote: "Internal note",
    ClientMessage: "Client message",
    StaffReply: "Support reply",
    Client: "Client",
    HelpDeskAgent: "Help-desk agent",
    Expert: "Expert",
    Admin: "Administrator",
    Ticket: "Ticket",
    Meeting: "Meeting",
    Subscription: "Subscription",
    ContactRequest: "Contact request",
    KpiPeriod: "KPI period",
    Published: "Published",
    Draft: "Draft",
    Archived: "Archived",
    organizationType: "organisation type",
    sector: "sector",
    region: "region",
    need: "need",
    dmaCategory: "DMA category",
    status: "status",
    assignee: "assignee",
    category: "category",
    type: "type",
    recommendation: "recommendation",
    tickets: "tickets",
    contacts: "contacts",
    meetings: "meetings",
    subscriptions: "subscriptions",
  },
  sq: {
    SME: "NVM",
    MidCap: "Mid-cap",
    PublicInstitution: "Institucion publik",
    Partner: "Partner",
    Other: "Tjetër",
    DIGITAL_BUSINESS_STRATEGY: "Strategji digjitale biznesi",
    DIGITAL_READINESS: "Gatishmëri digjitale",
    HUMAN_CENTRIC_DIGITALISATION: "Digjitalizim i orientuar te njerëzit",
    DATA_MANAGEMENT: "Menaxhimi i të dhënave",
    GREEN_DIGITALISATION: "Digjitalizim i gjelbër",
    AI_READINESS: "Gatishmëria për AI",
    AI_ACT_COMPLIANCE: "AI Act dhe pajtueshmëria",
    AI_USE_CASE: "Rast përdorimi i AI",
    AUTOMATION_AND_INTELLIGENCE: "Automatizim dhe inteligjencë",
    TEST_BEFORE_INVEST: "Testo para investimit",
    DIGITALIZATION_ROADMAP: "Udhërrëfyes digjitalizimi",
    DATA_GOVERNANCE: "Qeverisja e të dhënave",
    TRAINING_SKILLS: "Trajnime dhe aftësi",
    TRAINING_AND_SKILLS: "Trajnime dhe aftësi",
    FUNDING_SUPPORT: "Mbështetje financimi",
    FUNDING_AND_INVESTMENT: "Financim dhe investime",
    REFERRAL: "Referim",
    OTHER: "Tjetër",
    Low: "I ulët",
    Normal: "Normal",
    High: "I lartë",
    Urgent: "Urgjent",
    New: "E re",
    Responded: "Është përgjigjur",
    Handled: "E përpunuar",
    RegistrationInvited: "Ftuar për regjistrim",
    Triage: "Për shqyrtim",
    Assigned: "E caktuar",
    InProgress: "Në proces",
    WaitingForClient: "Në pritje të klientit",
    WaitingForExpert: "Në pritje të ekspertit",
    Resolved: "E zgjidhur",
    Closed: "E mbyllur",
    Invited: "I ftuar",
    Accepted: "Aktive",
    PendingPayment: "Në pritje të pagesës",
    PendingVerification: "Në pritje të verifikimit të email-it",
    Active: "Aktive",
    Inactive: "Joaktive",
    Expired: "E skaduar",
    Cancelled: "E anuluar",
    Requested: "I kërkuar",
    Confirmed: "I konfirmuar",
    Rejected: "I refuzuar",
    Completed: "I përfunduar",
    Online: "Online",
    Offline: "Me prani",
    Hybrid: "Hibrid",
    Consultation: "Konsultim",
    TechnicalReview: "Rishikim teknik",
    FollowUp: "Takim vijues",
    PendingApproval: "Në pritje të miratimit",
    Approved: "E miratuar",
    Suspended: "E pezulluar",
    SystemEvent: "Ngjarje e sistemit",
    InternalNote: "Shënim i brendshëm",
    ClientMessage: "Mesazh i klientit",
    StaffReply: "Përgjigje nga mbështetja",
    Client: "Klient",
    HelpDeskAgent: "Këshilltar i help-desk",
    Expert: "Ekspert",
    Admin: "Administrator",
    Ticket: "Tiketë",
    Meeting: "Takim",
    Subscription: "Abonim",
    ContactRequest: "Kërkesë kontakti",
    KpiPeriod: "Periudhë KPI",
    Published: "E publikuar",
    Draft: "Draft",
    Archived: "E arkivuar",
    organizationType: "lloji i organizatës",
    sector: "sektori",
    region: "rajoni",
    need: "nevoja",
    dmaCategory: "kategoria DMA",
    status: "statusi",
    assignee: "personi i caktuar",
    category: "kategoria",
    type: "lloji",
    recommendation: "rekomandimi",
    tickets: "tiketat",
    contacts: "kontaktet",
    meetings: "takimet",
    subscriptions: "abonimet",
  },
};

export function labelFor(value: string | null | undefined, language: Language) {
  if (!value) return "—";
  return values[language][value] ?? value.replaceAll("_", " ");
}

const systemEventCopy: Record<Language, Record<string, string>> = {
  mk: {
    TICKET_ASSIGNED: "Тикетот е доделен на тимот за поддршка на DigitMak.",
    TICKET_RECOMMENDATION_UPDATED: "Препораката за тикетот е ажурирана.",
    TICKET_RESOLVED: "Тикетот е решен со конечна препорака.",
    TICKET_CLOSED: "Тикетот е затворен.",
  },
  en: {
    TICKET_ASSIGNED: "The ticket was assigned to the DigitMak support team.",
    TICKET_RECOMMENDATION_UPDATED: "The ticket recommendation was updated.",
    TICKET_RESOLVED: "The ticket was resolved with a final recommendation.",
    TICKET_CLOSED: "The ticket was closed.",
  },
  sq: {
    TICKET_ASSIGNED: "Tiketa iu caktua ekipit të mbështetjes së DigitMak.",
    TICKET_RECOMMENDATION_UPDATED: "Rekomandimi i tiketës u përditësua.",
    TICKET_RESOLVED: "Tiketa u zgjidh me një rekomandim përfundimtar.",
    TICKET_CLOSED: "Tiketa u mbyll.",
  },
};

export function systemEventFor(body: string, language: Language) {
  if (body.startsWith("TICKET_STATUS_CHANGED:")) {
    const [, oldStatus, newStatus] = body.split(":");
    if (language === "mk")
      return `Статусот на тикетот е променет од ${labelFor(oldStatus, language)} во ${labelFor(newStatus, language)}.`;
    if (language === "sq")
      return `Statusi i tiketës ndryshoi nga ${labelFor(oldStatus, language)} në ${labelFor(newStatus, language)}.`;
    return `The ticket status changed from ${labelFor(oldStatus, language)} to ${labelFor(newStatus, language)}.`;
  }
  return systemEventCopy[language][body] ?? body;
}

export function ticketStatusClass(status: string) {
  if (["Resolved", "Closed"].includes(status)) return "status-complete";
  if (["Triage", "Assigned", "InProgress", "WaitingClient"].includes(status))
    return "status-progress";
  return "status-new";
}
