[CmdletBinding()]
param(
    [string]$OutputPath = '.env.production',
    [string]$Domain,
    [string]$AdminEmail,
    [string]$BrevoUsername,
    [string]$BrevoPassword,
    [string]$LetsEncryptEmail,
    [switch]$NonInteractive,
    [switch]$Force
)
$ErrorActionPreference = 'Stop'

if ((Test-Path -LiteralPath $OutputPath) -and -not $Force) { throw "$OutputPath already exists. Use -Force only when replacement is intentional." }
function Ask([string]$Label, [string]$Current, [string]$Default = '') {
    if ($Current) { return $Current }
    if ($NonInteractive) { return $Default }
    $suffix = if ($Default) { " [$Default]" } else { '' }
    $value = Read-Host "$Label$suffix"
    if ($value) { return $value }
    return $Default
}
function New-Secret([int]$Bytes = 48) {
    $buffer = New-Object byte[] $Bytes
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $generator.GetBytes($buffer) } finally { $generator.Dispose() }
    return [Convert]::ToBase64String($buffer).Replace('+','A').Replace('/','B').TrimEnd('=')
}

$Domain = Ask 'Production domain' $Domain 'portal.digitmak.mk'
$AdminEmail = Ask 'Bootstrap administrator email' $AdminEmail 'CHANGE_ME_ADMIN_EMAIL'
$BrevoUsername = Ask 'Brevo SMTP username' $BrevoUsername 'CHANGE_ME_BREVO_LOGIN'
$BrevoPassword = Ask 'Brevo SMTP key' $BrevoPassword 'CHANGE_ME_BREVO_SMTP_KEY'
$LetsEncryptEmail = Ask "Let's Encrypt operations email" $LetsEncryptEmail 'CHANGE_ME_OPERATIONS_EMAIL'
$dbPassword = New-Secret 36
$jwtKey = New-Secret 64
$adminPassword = "Dm1!$(New-Secret 30)"

$lines = @(
    '# Generated by deploy/setup-production.ps1. Keep this file protected and never commit it.',
    'POSTGRES_DB=digitmak',
    'POSTGRES_USER=digitmak',
    "POSTGRES_PASSWORD=$dbPassword",
    "PORTAL_DOMAIN=$Domain",
    "JWT_SIGNING_KEY=$jwtKey",
    'BREVO_SMTP_HOST=smtp-relay.brevo.com',
    'BREVO_SMTP_PORT=587',
    "BREVO_SMTP_USERNAME=$BrevoUsername",
    "BREVO_SMTP_PASSWORD=$BrevoPassword",
    'BREVO_FROM_EMAIL=info@digitmak.mk',
    'BREVO_FROM_NAME=DigitMak',
    "APP_PUBLIC_URL=https://$Domain",
    "ADMIN_BOOTSTRAP_EMAIL=$AdminEmail",
    "ADMIN_BOOTSTRAP_PASSWORD=$adminPassword",
    'UPLOADS_ROOT=/var/lib/digitmak-portal/uploads',
    'CLAMAV_HOST=clamav',
    'CLAMAV_PORT=3310',
    'MOODLE_BASE_URL=',
    'MOODLE_SSO_MODE=ExternalLink',
    'MOODLE_SSO_ENTRY_URL=',
    'MOODLE_SSO_SHARED_SECRET=',
    'GOOGLE_CALENDAR_CLIENT_ID=',
    'GOOGLE_CALENDAR_CLIENT_SECRET=',
    "GOOGLE_CALENDAR_REDIRECT_URI=https://$Domain/api/integrations/calendars/google/callback",
    'MICROSOFT_CALENDAR_CLIENT_ID=',
    'MICROSOFT_CALENDAR_CLIENT_SECRET=',
    'MICROSOFT_CALENDAR_TENANT_ID=common',
    "MICROSOFT_CALENDAR_REDIRECT_URI=https://$Domain/api/integrations/calendars/microsoft/callback",
    'BACKUP_ROOT=/var/backups/digitmak',
    'BACKUP_RETENTION_DAYS=30',
    "LETSENCRYPT_EMAIL=$LetsEncryptEmail"
)
[IO.File]::WriteAllLines((Join-Path (Get-Location) $OutputPath), $lines, [Text.UTF8Encoding]::new($false))
Write-Host "Created $OutputPath with generated database, JWT and administrator secrets."
if ($lines -match 'CHANGE_ME') { Write-Warning 'External account values are still placeholders. Fill them before validation.' }
Write-Host "Next: powershell -File deploy/validate-production.ps1"
