import type { Language } from "../shared/types";

export const localeFor = (language: Language) =>
  language === "en" ? "en-GB" : language === "sq" ? "sq-AL" : "mk-MK";

export const dashboardCopy = {
  mk: {
    ticket: {
      liveError:
        "Разговорот во живо моментално не е достапен; пораките сепак може да се испраќаат.",
      createError: "Тикетот не може да се креира.",
      accessRequired:
        "За креирање тикет е потребна одобрена организација и активна лична претплата.",
      sendError: "Пораката не може да се испрати.",
      uploadError: "Документот не може да се прикачи.",
      back: "Назад кон тикетите",
      noMessages: "Сè уште нема пораки.",
      recommendation: "ФИНАЛНА ПРЕПОРАКА",
      referral: "Упатување",
      messagePlaceholder: "Напишете порака...",
      messageLabel: "Порака",
      replyClient: "Одговор до клиент",
      send: "Испрати",
      attach: "Прикачи документ",
      attachments: "Прилози",
      noAttachments: "Нема прикачени документи.",
      download: "Преземи",
      preview: "Прегледај",
      myTickets: "Мои тикети",
      newTicket: "Нов тикет",
      category: "Категорија",
      priority: "Приоритет",
      title: "Наслов",
      description: "Опис",
      create: "Креирај тикет",
      empty: "Немате креирано тикети.",
    },
    meeting: {
      request: "Побарај состанок",
      subject: "Тема",
      description: "Опис",
      type: "Тип",
      online: "Онлајн",
      onsite: "Во живо",
      preferred: "Посакуван термин",
      end: "Крај",
      alternative: "Алтернативен временски прозорец",
      alternativeHint: "пр. работни денови 10-14",
      locationInput: "Локација за средба во живо",
      notes: "Белешки",
      submit: "Испрати барање",
      my: "Мои состаноци",
      pending: "Терминот се разгледува",
      location: "Локација",
      openOnline: "Отвори online состанок",
      cancel: "Откажи",
      empty: "Нема побарани состаноци.",
      requestError: "Состанокот не може да се побара.",
      cancelError: "Состанокот не може да се откаже.",
      calendar: "Сними календарска датотека (.ics)",
      calendarHelp:
        "За Outlook отворете ја .ics датотеката директно. За Google Calendar внесете ја преку Settings, потоа Import & export и Import. Работи за онлајн и состаноци во живо.",
    },
    client: {
      overview: "Преглед",
      organizationSubscription: "Организација и претплата",
      tickets: "Мои тикети",
      meetings: "Состаноци",
      profile: "Профил",
      notifications: "Известувања",
      noNotifications: "Нема известувања.",
      user: "Корисник",
      signedIn: "Најавен корисник",
      registerOrganization: "Регистрирај организација",
      administration: "Администрација",
      workspace: "Работен простор",
      logout: "Одјави се",
      portal: "КЛИЕНТСКИ ПОРТАЛ",
      welcome: "Добредојдовте",
      newTicket: "Нов тикет",
      activeTickets: "Активни тикети",
      loading: "Се вчитува...",
      activeRequests: "Вашите активни барања",
      nextMeeting: "Следен состанок",
      noConfirmed: "Нема потврден термин",
      subscription: "Претплата",
      invitationUpper: "ПОКАНА",
      inactiveUpper: "НЕАКТИВНА",
      validUntil: "Важи до",
      annual: "Лична годишна претплата",
      recentTickets: "Последни тикети",
      seeAll: "Види ги сите",
      noTickets: "Немате креирано тикети.",
      noOrganization: "Немате активна организација.",
      createOrJoin:
        "Создајте организација или побарајте членство во постоечка.",
      organization: "Организација",
      type: "Тип",
      sector: "Сектор",
      region: "Регион",
      status: "Статус",
      invitation: "Покана",
      noInvitation: "Нема покана",
      invitationUntil: "Поканата важи до",
      acceptInvitation: "Прифати покана",
      pendingPayment: "Се очекува потврда за офлајн уплата од администратор.",
      paymentInstructions: "Инструкции за банкарска уплата",
      paymentRecipient: "Примач",
      paymentBank: "Банка",
      paymentAccount: "Трансакциска сметка",
      paymentAmount: "Износ",
      paymentPurpose: "Цел на дознака",
      paymentReference: "Повикување на број / референца",
      paymentHelp: "Помош за уплата",
      paymentNotConfigured:
        "Официјалните инструкции за уплата сè уште не се внесени. Контактирајте го DigitMak пред да извршите уплата.",
      activeUntil: "Активна до",
      invitationMissing: "Администраторот сè уште нема испратено покана.",
      invitationError: "Поканата не може да се прифати.",
      profileLoading: "Се вчитува профилот...",
      profileSettings: "Профил и поставки",
      email: "Е-пошта",
      firstName: "Име",
      lastName: "Презиме",
      phone: "Телефон",
      language: "Јазик",
      saved: "Профилот е зачуван.",
      saveError: "Профилот не може да се зачува.",
      save: "Зачувај",
    },
  },
  en: {
    ticket: {
      liveError:
        "Live chat is temporarily unavailable; messages can still be sent.",
      createError: "The ticket could not be created.",
      accessRequired:
        "An approved organisation and an active personal subscription are required to create a ticket.",
      sendError: "The message could not be sent.",
      uploadError: "The document could not be uploaded.",
      back: "Back to tickets",
      noMessages: "There are no messages yet.",
      recommendation: "FINAL RECOMMENDATION",
      referral: "Referral",
      messagePlaceholder: "Write a message...",
      messageLabel: "Message",
      replyClient: "Reply to client",
      send: "Send",
      attach: "Attach document",
      attachments: "Attachments",
      noAttachments: "No documents are attached.",
      download: "Download",
      preview: "Preview",
      myTickets: "My tickets",
      newTicket: "New ticket",
      category: "Category",
      priority: "Priority",
      title: "Title",
      description: "Description",
      create: "Create ticket",
      empty: "You have not created any tickets.",
    },
    meeting: {
      request: "Request a meeting",
      subject: "Subject",
      description: "Description",
      type: "Type",
      online: "Online",
      onsite: "In person",
      preferred: "Preferred start",
      end: "End",
      alternative: "Alternative time window",
      alternativeHint: "e.g. weekdays 10-14",
      locationInput: "In-person location",
      notes: "Notes",
      submit: "Send request",
      my: "My meetings",
      pending: "Time is being reviewed",
      location: "Location",
      openOnline: "Open online meeting",
      cancel: "Cancel",
      empty: "No meetings requested.",
      requestError: "The meeting could not be requested.",
      cancelError: "The meeting could not be cancelled.",
      calendar: "Save calendar file (.ics)",
      calendarHelp:
        "Open the .ics file directly in Outlook. For Google Calendar, use Settings, then Import & export and Import. Online and in-person meetings are both included.",
    },
    client: {
      overview: "Overview",
      organizationSubscription: "Organisation and subscription",
      tickets: "My tickets",
      meetings: "Meetings",
      profile: "Profile",
      notifications: "Notifications",
      noNotifications: "No notifications.",
      user: "User",
      signedIn: "Signed-in user",
      registerOrganization: "Register organisation",
      administration: "Administration",
      workspace: "Staff workspace",
      logout: "Sign out",
      portal: "CLIENT PORTAL",
      welcome: "Welcome",
      newTicket: "New ticket",
      activeTickets: "Active tickets",
      loading: "Loading...",
      activeRequests: "Your active requests",
      nextMeeting: "Next meeting",
      noConfirmed: "No confirmed meeting",
      subscription: "Subscription",
      invitationUpper: "INVITATION",
      inactiveUpper: "INACTIVE",
      validUntil: "Valid until",
      annual: "Personal annual subscription",
      recentTickets: "Recent tickets",
      seeAll: "See all",
      noTickets: "You have not created any tickets.",
      noOrganization: "You do not have an active organisation.",
      createOrJoin:
        "Create an organisation or request membership in an existing one.",
      organization: "Organisation",
      type: "Type",
      sector: "Sector",
      region: "Region",
      status: "Status",
      invitation: "Invitation",
      noInvitation: "No invitation",
      invitationUntil: "The invitation is valid until",
      acceptInvitation: "Accept invitation",
      pendingPayment:
        "Administrator confirmation of the offline payment is pending.",
      paymentInstructions: "Bank payment instructions",
      paymentRecipient: "Recipient",
      paymentBank: "Bank",
      paymentAccount: "Bank account",
      paymentAmount: "Amount",
      paymentPurpose: "Payment purpose",
      paymentReference: "Payment reference",
      paymentHelp: "Payment support",
      paymentNotConfigured:
        "Official payment instructions have not been entered yet. Contact DigitMak before making a payment.",
      activeUntil: "Active until",
      invitationMissing: "The administrator has not sent an invitation yet.",
      invitationError: "The invitation could not be accepted.",
      profileLoading: "Loading profile...",
      profileSettings: "Profile and settings",
      email: "Email",
      firstName: "First name",
      lastName: "Last name",
      phone: "Phone",
      language: "Language",
      saved: "Profile saved.",
      saveError: "The profile could not be saved.",
      save: "Save",
    },
  },
  sq: {
    ticket: {
      liveError:
        "Biseda live nuk është përkohësisht e disponueshme; mesazhet ende mund të dërgohen.",
      createError: "Tiketa nuk mund të krijohej.",
      accessRequired:
        "Për të krijuar tiketë nevojiten një organizatë e miratuar dhe një abonim personal aktiv.",
      sendError: "Mesazhi nuk mund të dërgohej.",
      uploadError: "Dokumenti nuk mund të ngarkohej.",
      back: "Kthehu te tiketаt",
      noMessages: "Ende nuk ka mesazhe.",
      recommendation: "REKOMANDIMI PËRFUNDIMTAR",
      referral: "Referimi",
      messagePlaceholder: "Shkruani mesazh...",
      messageLabel: "Mesazh",
      replyClient: "Përgjigje klientit",
      send: "Dërgo",
      attach: "Ngarko dokument",
      attachments: "Shtojcat",
      noAttachments: "Nuk ka dokumente të bashkëngjitura.",
      download: "Shkarko",
      preview: "Shiko",
      myTickets: "Tiketat e mia",
      newTicket: "Tiketë e re",
      category: "Kategoria",
      priority: "Prioriteti",
      title: "Titulli",
      description: "Përshkrimi",
      create: "Krijo tiketë",
      empty: "Nuk keni krijuar tiketa.",
    },
    meeting: {
      request: "Kërko takim",
      subject: "Tema",
      description: "Përshkrimi",
      type: "Lloji",
      online: "Online",
      onsite: "Me prani",
      preferred: "Fillimi i preferuar",
      end: "Fundi",
      alternative: "Dritare alternative kohore",
      alternativeHint: "p.sh. ditëve të punës 10-14",
      locationInput: "Vendndodhja e takimit",
      notes: "Shënime",
      submit: "Dërgo kërkesën",
      my: "Takimet e mia",
      pending: "Orari po shqyrtohet",
      location: "Vendndodhja",
      openOnline: "Hap takimin online",
      cancel: "Anulo",
      empty: "Nuk ka takime të kërkuara.",
      requestError: "Takimi nuk mund të kërkohej.",
      cancelError: "Takimi nuk mund të anulohej.",
      calendar: "Ruaj skedarin e kalendarit (.ics)",
      calendarHelp:
        "Hapeni skedarin .ics drejtpërdrejt në Outlook. Për Google Calendar përdorni Settings, pastaj Import & export dhe Import. Përfshihen takimet online dhe me prani.",
    },
    client: {
      overview: "Përmbledhje",
      organizationSubscription: "Organizata dhe abonimi",
      tickets: "Tiketat e mia",
      meetings: "Takimet",
      profile: "Profili",
      notifications: "Njoftimet",
      noNotifications: "Nuk ka njoftime.",
      user: "Përdorues",
      signedIn: "Përdorues i kyçur",
      registerOrganization: "Regjistro organizatë",
      administration: "Administrimi",
      workspace: "Hapësira e stafit",
      logout: "Dil",
      portal: "PORTALI I KLIENTIT",
      welcome: "Mirë se vini",
      newTicket: "Tiketë e re",
      activeTickets: "Tiketa aktive",
      loading: "Duke u ngarkuar...",
      activeRequests: "Kërkesat tuaja aktive",
      nextMeeting: "Takimi i ardhshëm",
      noConfirmed: "Nuk ka takim të konfirmuar",
      subscription: "Abonimi",
      invitationUpper: "FTESË",
      inactiveUpper: "JOAKTIV",
      validUntil: "Vlen deri më",
      annual: "Abonim personal vjetor",
      recentTickets: "Tiketat e fundit",
      seeAll: "Shiko të gjitha",
      noTickets: "Nuk keni krijuar tiketa.",
      noOrganization: "Nuk keni organizatë aktive.",
      createOrJoin:
        "Krijoni organizatë ose kërkoni anëtarësim në një ekzistuese.",
      organization: "Organizata",
      type: "Lloji",
      sector: "Sektori",
      region: "Rajoni",
      status: "Statusi",
      invitation: "Ftesë",
      noInvitation: "Nuk ka ftesë",
      invitationUntil: "Ftesa vlen deri më",
      acceptInvitation: "Prano ftesën",
      pendingPayment: "Pritet konfirmimi i pagesës offline nga administratori.",
      paymentInstructions: "Udhëzimet për pagesë bankare",
      paymentRecipient: "Përfituesi",
      paymentBank: "Banka",
      paymentAccount: "Llogaria bankare",
      paymentAmount: "Shuma",
      paymentPurpose: "Qëllimi i pagesës",
      paymentReference: "Referenca e pagesës",
      paymentHelp: "Ndihmë për pagesën",
      paymentNotConfigured:
        "Udhëzimet zyrtare të pagesës ende nuk janë vendosur. Kontaktoni DigitMak para pagesës.",
      activeUntil: "Aktiv deri më",
      invitationMissing: "Administratori ende nuk ka dërguar ftesë.",
      invitationError: "Ftesa nuk mund të pranohej.",
      profileLoading: "Duke ngarkuar profilin...",
      profileSettings: "Profili dhe cilësimet",
      email: "Email",
      firstName: "Emri",
      lastName: "Mbiemri",
      phone: "Telefoni",
      language: "Gjuha",
      saved: "Profili u ruajt.",
      saveError: "Profili nuk mund të ruhej.",
      save: "Ruaj",
    },
  },
} as const;
