export const uiCopy = {
  mk: {
    help: {
      title: "Од прашање до практична препорака.",
      lead: "Активните претплатници добиваат безбеден тикет, разговор во реално време и директен пристап до советник.",
      notice:
        "AI help desk обезбедува почетни насоки и препораки. Не претставува формален правен совет или регулаторно одобрение.",
      access: "ПРИСТАП ЗА ПРЕТПЛАТНИЦИ",
      login: "Најавете се во порталот",
      email: "Е-пошта",
      password: "Лозинка",
      submit: "Најави се",
      noAccount: "Немате сметка?",
      register: "Регистрирајте се.",
      forgot: "Ја заборавивте лозинката?",
      error: "Најавувањето не успеа.",
      invalidCredentials:
        "Е-поштата или лозинката не се точни. Проверете ги податоците и обидете се повторно.",
      serverUnavailable:
        "Серверот не е активен или не може да се достигне. Стартувајте го START-BACKEND.cmd и обидете се повторно.",
      accountUnavailable:
        "Сметката нема дозвола за најава. Проверете дали е активирана.",
    },
    dma: {
      kicker: "ПРОЦЕНКА НА ДИГИТАЛНА ЗРЕЛОСТ",
      title: "Кажете ни што сакате да постигнете.",
      lead: "Кратка DMA проценка за да ве насочиме кон соодветна DigitMak услуга.",
      response: "Одговор во рок од 2 работни дена",
      support: "МК, EN и SQ поддршка",
      consultation: "Онлајн или консултација во живо",
      organization: "Организација",
      name: "Име",
      type: "Тип",
      sector: "Сектор",
      municipality: "Општина",
      region: "Регион",
      website: "Веб-страница",
      employees: "Број на вработени",
      contact: "Контакт",
      fullName: "Име и презиме",
      email: "Е-пошта",
      phone: "Телефон",
      language: "Јазик",
      maturity: "Дигитална зрелост и потреба",
      selfRating: "Самооценка 1–5",
      beginner: "Почетно",
      advanced: "Напредно",
      mainNeed: "Главна потреба",
      ai: "Вештачка интелигенција",
      digitalization: "Дигитализација",
      training: "Обука",
      funding: "Финансирање",
      other: "Друго",
      challenge: "Деловен или јавен предизвик",
      tools: "Тековен софтвер/алатки",
      dataSources: "Тековни извори на податоци",
      usesAi: "Користите AI?",
      no: "Не",
      yes: "Да",
      timeline: "Посакуван рок",
      useCase: "AI use-case идеја",
      privacyConcerns: "Privacy/compliance грижи",
      trainingNeeds: "Потреби за обука",
      format: "Формат на консултација",
      noPreference: "Без предност",
      online: "Онлајн",
      inPerson: "Во живо",
      aiAct: "Заинтересиран/а сум за AI Act насоки.",
      consent: "Се согласувам да бидам контактиран/а.",
      privacy: "Ја прифаќам политиката за приватност.",
      send: "Испрати барање",
      received: "Барањето е примено.",
      confirmation:
        "Испратена е потврда на вашата е-пошта. Тимот на DigitMak ќе ве контактира.",
      newRequest: "Ново барање",
      error: "Барањето не може да се испрати.",
    },
    training: {
      kicker: "ОБУКИ И ВЕШТИНИ",
      title: "Знаење за практична дигитална трансформација.",
      lead: "Каталогот за обуки е подготвен за поврзување со Moodle. До целосната SSO интеграција, тимот на DigitMak ќе предложи соодветна обука преку контакт барање.",
      aiTitle: "AI основи",
      aiText:
        "Вовед во одговорна и практична примена на вештачка интелигенција.",
      dataTitle: "Управување со податоци",
      dataText: "Квалитет, приватност и управување со податоци.",
      actTitle: "AI Act",
      actText: "Прва ориентација за обврски и управување со ризик.",
      action: "Побарај обука",
    },
    legal: {
      kicker: "ПРАВНИ ИНФОРМАЦИИ",
      updated:
        "Последно ажурирање: 21 јули 2026. Финалниот текст треба да биде одобрен од овластено правно лице на DigitMak пред production објава.",
      privacyTitle: "Политика за приватност",
      privacySections: [
        [
          "Кои податоци ги обработуваме",
          "Порталот обработува податоци за корисничка сметка, организација, контакт барања, тикети, пораки, состаноци, прикачени документи и технички audit записи.",
        ],
        [
          "Зошто ги користиме",
          "Податоците се користат за обезбедување на договорените услуги, корисничка поддршка, безбедност, исполнување законски обврски и подобрување на услугата.",
        ],
        [
          "Пристап и задржување",
          "Пристап имаат само овластени корисници според нивната улога. Роковите за задржување и постапката за бришење мора да се утврдат во официјалната политика на DigitMak.",
        ],
        [
          "Ваши права",
          "За пристап, исправка, ограничување или бришење на лични податоци, испратете барање преку контакт формата.",
        ],
      ],
      termsTitle: "Услови за користење",
      termsSections: [
        [
          "Намена на порталот",
          "Порталот овозможува пристап до DigitMak услуги, AI Help Desk поддршка, тикети, состаноци и размена на документи за одобрени организации и активни претплатници.",
        ],
        [
          "AI Help Desk",
          "Одговорите и препораките имаат информативна и советодавна намена. Тие не се формален правен совет, сертификација или регулаторно одобрение.",
        ],
        [
          "Корисничка одговорност",
          "Корисникот е должен да внесе точни податоци, да ја заштити сметката и да не прикачува незаконска, злонамерна или непотребно чувствителна содржина.",
        ],
        [
          "Достапност",
          "DigitMak може да ја ограничи или суспендира сметката при злоупотреба, безбедносен ризик или истечена претплата.",
        ],
      ],
    },
  },
  en: {
    help: {
      title: "From question to practical recommendation.",
      lead: "Active subscribers receive a secure ticket, real-time conversation and direct access to an adviser.",
      notice:
        "The AI Help Desk provides initial guidance and recommendations. It is not formal legal advice or regulatory approval.",
      access: "SUBSCRIBER ACCESS",
      login: "Sign in to the portal",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      noAccount: "No account yet?",
      register: "Create one.",
      forgot: "Forgot your password?",
      error: "Sign-in failed.",
      invalidCredentials:
        "The email address or password is incorrect. Check the details and try again.",
      serverUnavailable:
        "The server is not running or cannot be reached. Start START-BACKEND.cmd and try again.",
      accountUnavailable:
        "This account is not allowed to sign in. Check that it has been activated.",
    },
    dma: {
      kicker: "DIGITAL MATURITY ASSESSMENT",
      title: "Tell us what you want to achieve.",
      lead: "A concise DMA assessment that helps us guide you to the right DigitMak service.",
      response: "Response within 2 working days",
      support: "MK, EN and SQ support",
      consultation: "Online or in-person consultation",
      organization: "Organisation",
      name: "Name",
      type: "Type",
      sector: "Sector",
      municipality: "Municipality",
      region: "Region",
      website: "Website",
      employees: "Number of employees",
      contact: "Contact",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
      language: "Language",
      maturity: "Digital maturity and need",
      selfRating: "Self-rating 1–5",
      beginner: "Beginner",
      advanced: "Advanced",
      mainNeed: "Main need",
      ai: "Artificial intelligence",
      digitalization: "Digitalisation",
      training: "Training",
      funding: "Funding",
      other: "Other",
      challenge: "Business or public-service challenge",
      tools: "Current software/tools",
      dataSources: "Current data sources",
      usesAi: "Do you use AI?",
      no: "No",
      yes: "Yes",
      timeline: "Desired timeline",
      useCase: "AI use-case idea",
      privacyConcerns: "Privacy/compliance concerns",
      trainingNeeds: "Training needs",
      format: "Consultation format",
      noPreference: "No preference",
      online: "Online",
      inPerson: "In person",
      aiAct: "I am interested in AI Act guidance.",
      consent: "I agree to be contacted.",
      privacy: "I accept the privacy policy.",
      send: "Send request",
      received: "Request received.",
      confirmation:
        "A confirmation was sent to your email. The DigitMak team will contact you.",
      newRequest: "New request",
      error: "The request could not be sent.",
    },
    training: {
      kicker: "TRAINING & SKILLS",
      title: "Knowledge for practical digital transformation.",
      lead: "The training catalogue is ready for Moodle integration. Until full SSO is connected, the DigitMak team will recommend suitable training through a contact request.",
      aiTitle: "AI foundations",
      aiText:
        "An introduction to responsible and practical use of artificial intelligence.",
      dataTitle: "Data governance",
      dataText: "Data quality, privacy and governance.",
      actTitle: "AI Act",
      actText: "Initial orientation on obligations and risk management.",
      action: "Request training",
    },
    legal: {
      kicker: "LEGAL INFORMATION",
      updated:
        "Last updated: 21 July 2026. The final text must be approved by an authorised DigitMak legal representative before production publication.",
      privacyTitle: "Privacy Policy",
      privacySections: [
        [
          "Data we process",
          "The portal processes account, organisation, contact request, ticket, message, meeting, uploaded document and technical audit data.",
        ],
        [
          "Why we use it",
          "Data is used to provide contracted services, user support, security, legal compliance and service improvement.",
        ],
        [
          "Access and retention",
          "Only authorised users have access according to their role. Retention and deletion periods must be defined in DigitMak's official policy.",
        ],
        [
          "Your rights",
          "To request access, correction, restriction or deletion of personal data, submit a request through the contact form.",
        ],
      ],
      termsTitle: "Terms of Use",
      termsSections: [
        [
          "Portal purpose",
          "The portal provides access to DigitMak services, AI Help Desk support, tickets, meetings and document exchange for approved organisations and active subscribers.",
        ],
        [
          "AI Help Desk",
          "Answers and recommendations are informational and advisory. They are not formal legal advice, certification or regulatory approval.",
        ],
        [
          "User responsibility",
          "Users must provide accurate data, protect their account and avoid uploading unlawful, malicious or unnecessarily sensitive content.",
        ],
        [
          "Availability",
          "DigitMak may limit or suspend an account in case of abuse, security risk or expired subscription.",
        ],
      ],
    },
  },
  sq: {
    help: {
      title: "Nga pyetja te rekomandimi praktik.",
      lead: "Abonentët aktivë marrin tiketë të sigurt, bisedë në kohë reale dhe qasje të drejtpërdrejtë te këshilltari.",
      notice:
        "AI Help Desk ofron udhëzime dhe rekomandime fillestare. Nuk është këshillë formale juridike apo miratim rregullator.",
      access: "QASJE PËR ABONENTËT",
      login: "Hyni në portal",
      email: "Email",
      password: "Fjalëkalimi",
      submit: "Hyr",
      noAccount: "Nuk keni llogari?",
      register: "Regjistrohuni.",
      forgot: "Keni harruar fjalëkalimin?",
      error: "Hyrja dështoi.",
      invalidCredentials:
        "Email-i ose fjalëkalimi është i pasaktë. Kontrolloni të dhënat dhe provoni përsëri.",
      serverUnavailable:
        "Serveri nuk është aktiv ose nuk mund të arrihet. Nisni START-BACKEND.cmd dhe provoni përsëri.",
      accountUnavailable:
        "Kjo llogari nuk lejohet të hyjë. Kontrolloni nëse është aktivizuar.",
    },
    dma: {
      kicker: "VLERËSIMI I PJEKURISË DIGJITALE",
      title: "Na tregoni çfarë dëshironi të arrini.",
      lead: "Një vlerësim i shkurtër DMA për t'ju orientuar te shërbimi i duhur DigitMak.",
      response: "Përgjigje brenda 2 ditësh pune",
      support: "Mbështetje MK, EN dhe SQ",
      consultation: "Konsultim online ose me prani",
      organization: "Organizata",
      name: "Emri",
      type: "Lloji",
      sector: "Sektori",
      municipality: "Komuna",
      region: "Rajoni",
      website: "Uebfaqja",
      employees: "Numri i punonjësve",
      contact: "Kontakti",
      fullName: "Emri dhe mbiemri",
      email: "Email",
      phone: "Telefoni",
      language: "Gjuha",
      maturity: "Pjekuria dhe nevoja digjitale",
      selfRating: "Vetëvlerësim 1–5",
      beginner: "Fillestar",
      advanced: "Avancuar",
      mainNeed: "Nevoja kryesore",
      ai: "Inteligjenca artificiale",
      digitalization: "Digjitalizimi",
      training: "Trajnimi",
      funding: "Financimi",
      other: "Tjetër",
      challenge: "Sfida e biznesit ose shërbimit publik",
      tools: "Softueri/mjetet aktuale",
      dataSources: "Burimet aktuale të të dhënave",
      usesAi: "A përdorni AI?",
      no: "Jo",
      yes: "Po",
      timeline: "Afati i dëshiruar",
      useCase: "Ide për përdorimin e AI",
      privacyConcerns: "Shqetësime për privatësi/pajtueshmëri",
      trainingNeeds: "Nevojat për trajnim",
      format: "Formati i konsultimit",
      noPreference: "Pa preferencë",
      online: "Online",
      inPerson: "Me prani",
      aiAct: "Jam i/e interesuar për udhëzime mbi AI Act.",
      consent: "Pajtohem të kontaktohem.",
      privacy: "E pranoj politikën e privatësisë.",
      send: "Dërgo kërkesën",
      received: "Kërkesa u pranua.",
      confirmation:
        "Konfirmimi u dërgua në emailin tuaj. Ekipi DigitMak do t'ju kontaktojë.",
      newRequest: "Kërkesë e re",
      error: "Kërkesa nuk mund të dërgohej.",
    },
    training: {
      kicker: "TRAJNIME DHE AFTËSI",
      title: "Njohuri për transformim praktik digjital.",
      lead: "Katalogu i trajnimeve është gati për integrim me Moodle. Deri në lidhjen e plotë SSO, ekipi DigitMak do të rekomandojë trajnim përmes kërkesës së kontaktit.",
      aiTitle: "Bazat e AI",
      aiText:
        "Hyrje në përdorimin e përgjegjshëm dhe praktik të inteligjencës artificiale.",
      dataTitle: "Qeverisja e të dhënave",
      dataText: "Cilësi, privatësi dhe qeverisje e të dhënave.",
      actTitle: "AI Act",
      actText: "Orientim fillestar mbi detyrimet dhe menaxhimin e rrezikut.",
      action: "Kërko trajnim",
    },
    legal: {
      kicker: "INFORMACION LIGJOR",
      updated:
        "Përditësuar më 21 korrik 2026. Teksti përfundimtar duhet të miratohet nga një përfaqësues ligjor i autorizuar i DigitMak para publikimit.",
      privacyTitle: "Politika e Privatësisë",
      privacySections: [
        [
          "Të dhënat që përpunojmë",
          "Portali përpunon të dhëna të llogarisë, organizatës, kërkesave të kontaktit, tiketave, mesazheve, takimeve, dokumenteve dhe auditimit teknik.",
        ],
        [
          "Pse i përdorim",
          "Të dhënat përdoren për shërbime, mbështetje, siguri, detyrime ligjore dhe përmirësim të shërbimit.",
        ],
        [
          "Qasja dhe ruajtja",
          "Qasje kanë vetëm përdoruesit e autorizuar sipas rolit. Afatet e ruajtjes dhe fshirjes përcaktohen në politikën zyrtare të DigitMak.",
        ],
        [
          "Të drejtat tuaja",
          "Për qasje, korrigjim, kufizim ose fshirje të të dhënave, dërgoni kërkesë përmes formularit të kontaktit.",
        ],
      ],
      termsTitle: "Kushtet e Përdorimit",
      termsSections: [
        [
          "Qëllimi i portalit",
          "Portali jep qasje në shërbimet DigitMak, AI Help Desk, tiketa, takime dhe dokumente për organizata të miratuara dhe abonentë aktivë.",
        ],
        [
          "AI Help Desk",
          "Përgjigjet janë informative dhe këshilluese. Ato nuk janë këshillë formale juridike, certifikim apo miratim rregullator.",
        ],
        [
          "Përgjegjësia e përdoruesit",
          "Përdoruesi duhet të japë të dhëna të sakta, të mbrojë llogarinë dhe të mos ngarkojë përmbajtje të paligjshme, keqdashëse ose tepër të ndjeshme.",
        ],
        [
          "Disponueshmëria",
          "DigitMak mund të kufizojë ose pezullojë llogarinë në rast abuzimi, rreziku sigurie ose abonimi të skaduar.",
        ],
      ],
    },
  },
} as const;
