import type { Language } from "../shared/types";

type Copy = Record<string, string>;

const mk: Copy = {
  actionError: "Акцијата не успеа.",
  loadOrganizationError: "Организацијата не може да се вчита.",
  decisionError: "Одлуката не може да се зачува.",
  noStaffAccess: "Немате staff пристап.",
  noAdminAccess: "Немате администраторски пристап.",
  back: "Назад",
  details: "Детали",
  triage: "Клиентски тикети",
  calendarMeetings: "Календар и состаноци",
  contactRequests: "Контакт барања",
  clientPortal: "Клиентски портал",
  administration: "Администрација",
  workspace: "Работен простор",
  staffWorkspace: "РАБОТЕН ПРОСТОР ЗА ПОДДРШКА",
  administrator: "Администратор",
  adminCenter: "АДМИН КОНТРОЛЕН ЦЕНТАР",
  new: "Нови",
  inProgress: "Во тек",
  urgent: "Итни",
  ticketsForWork: "Тикети за обработка",
  start: "Почеток",
  end: "Крај",
  assignedAdvisor: "Доделен советник",
  choose: "Избери",
  location: "Локација",
  notes: "Белешки",
  confirm: "Потврди",
  reject: "Одбиј",
  complete: "Заврши",
  publicDma: "Јавни DMA барања",
  organization: "Организација",
  close: "Затвори",
  employees: "вработени",
  activeContacts: "Активни контакти",
  downloadCalendar: "Преземи staff календар (.ics)",
  liveDisconnected: "Разговорот во живо не е поврзан.",
  sendError: "Пораката не може да се испрати.",
  attachments: "Прилози од тикетот",
  attachmentsHelp:
    "Сите документи што клиентот или тимот ги прикачиле на овој тикет.",
  noAttachments: "На овој тикет нема прикачени документи.",
  attachDocument: "Прикачи документ",
  attachmentDownloadError: "Документот не може да се преземе.",
  attachmentUploadError: "Документот не може да се прикачи.",
  assignment: "Доделување",
  noExpert: "Без експерт",
  assign: "Додели",
  begin: "Започни",
  replyClient: "Јавен одговор",
  send: "Испрати",
  internalNote: "Внатрешна белешка",
  saveNote: "Зачувај белешка",
  finalRecommendation: "Финална препорака",
  practicalRecommendation: "Практична препорака",
  referralRecommendation: "Препорака за упатување",
  resolveTicket: "Реши тикет",
  overview: "Преглед",
  organizations: "Организации",
  subscriptions: "Претплати",
  contacts: "Контакт барања",
  tickets: "Тикети",
  documents: "Документи",
  allTicketDocuments: "Сите прилози од тикети",
  allTicketDocumentsHelp:
    "Централен преглед на документите прикачени од клиентите и тимот за поддршка.",
  noTicketDocuments: "Нема прикачени документи",
  noTicketDocumentsHelp:
    "Документите ќе се појават тука веднаш штом ќе бидат прикачени на тикет.",
  noContactRequests: "Нема нови контакт барања",
  noContactRequestsHelp:
    "Овде се прикажуваат барањата испратени преку јавната контакт-форма.",
  users: "Корисници",
  content: "Содржина",
  reports: "Извештаи",
  evidence: "Доказни документи",
  settings: "Поставки",
  audit: "Ревизиски записи",
  activeSubscriptions: "Активни претплати",
  expiredCancelled: "истечени/откажани",
  aiActRequests: "AI Act барања",
  publicInstitutions: "јавни институции",
  members: "Членови",
  approve: "Одобри",
  suspend: "Суспендирај",
  reactivate: "Повторно активирај",
  renewSubscription: "Обнови претплата",
  newInvitation: "Нова покана",
  user: "Корисник",
  sendInvitation: "Испрати покана",
  reference: "Референца",
  note: "Белешка",
  activate: "Активирај",
  confirmOfflinePayment: "Потврди офлајн уплата",
  pendingPaymentInstruction:
    "Овие клиенти чекаат потврда. Внесете референца од уплатата и притиснете „Активирај“.",
  paymentSettings: "Инструкции за уплата",
  paymentSettingsHelp:
    "Внесете ги само официјалните банкарски податоци на DigitMak. Клиентите со статус „Се чека уплата“ ќе ги гледаат овие информации.",
  paymentRecipient: "Примач",
  paymentBank: "Банка",
  paymentAccount: "Трансакциска сметка",
  paymentAmount: "Износ",
  paymentCurrency: "Валута",
  paymentPurpose: "Цел на дознака",
  paymentReferenceGuide: "Упатство за повикување на број / референца",
  paymentSupportEmail: "Е-пошта за помош при уплата",
  savePaymentSettings: "Зачувај инструкции за уплата",
  cancel: "Откажи",
  validUntil: "Важи до",
  handled: "Означи како обработено",
  inviteRegistration: "Покани регистрација",
  emailReply: "Одговор по е-пошта",
  adminTicketOverview: "Администраторски преглед на тикети",
  usersRoles: "Корисници и улоги",
  addRole: "Додај улога",
  deactivate: "Деактивирај",
  service: "Услуга",
  publicPage: "Јавна страница",
  aiHelpSubscriptions: "AI Help Desk претплати",
  confirmedMeetings: "Потврдени состаноци",
  referrals: "Препораки за упатување",
  detailedReports: "Детални извештаи",
  contactsBreakdown: "Контакти",
  ticketsBreakdown: "Тикети",
  meetingsBreakdown: "Состаноци",
  referralsBreakdown: "Упатувања",
  exportData: "Извоз на извештаи",
  downloadExcel: "Преземи Excel",
  downloadCsv: "Преземи CSV",
  groupBy: "групирано по",
  newEvidence: "Ново доказно досие",
  relatedType: "Поврзан тип",
  relatedId: "Поврзан ID",
  kpiCategory: "KPI категорија",
  period: "Период",
  template: "Образец",
  file: "Датотека",
  uploadEvidence: "Прикачи доказ",
  evidenceRegister: "Регистар на доказни документи",
  download: "Преземи",
  preview: "Прегледај",
  previewBlocked:
    "Прегледот е блокиран од прелистувачот. Дозволете pop-up или преземете го документот.",
  templateRegister: "Обрасци за доказни документи",
  downloadBlank: "Преземи Excel образец",
  selectTemplate: "Избери образец",
  chooseEvidenceFile: "Изберете доказна датотека.",
  evidenceDownloadError: "Доказната датотека не може да се преземе.",
  reportDownloadError: "Извештајот не може да се преземе.",
  systemSetting: "Системска поставка",
  key: "Клуч",
  value: "Вредност",
  description: "Опис",
  save: "Зачувај",
  systemActivities: "Непроменливи системски активности",
  status: "Статус",
  category: "Категорија",
  title: "Наслов",
  slug: "URL ознака",
  created: "Креирано",
  emailVerified: "Е-пошта потврдена",
  staffArea: "Работен простор за поддршка",
  onlineLink: "Онлајн врска",
  helpDeskAgent: "Help-desk советник",
  expert: "Експерт",
  clientOrganization: "КЛИЕНТСКА ОРГАНИЗАЦИЈА",
  dmaContactRequest: "DMA КОНТАКТ БАРАЊЕ",
  primaryContact: "примарен контакт",
  dmaCategory: "Внатрешна DMA категорија",
};

const en: Copy = {
  actionError: "The action failed.",
  loadOrganizationError: "The organisation could not be loaded.",
  decisionError: "The decision could not be saved.",
  noStaffAccess: "You do not have staff access.",
  noAdminAccess: "You do not have administrator access.",
  back: "Back",
  details: "Details",
  triage: "Client tickets",
  calendarMeetings: "Calendar and meetings",
  contactRequests: "Contact requests",
  clientPortal: "Client portal",
  administration: "Administration",
  workspace: "Workspace",
  staffWorkspace: "STAFF WORKSPACE",
  administrator: "Administrator",
  adminCenter: "ADMIN CONTROL CENTER",
  new: "New",
  inProgress: "In progress",
  urgent: "Urgent",
  ticketsForWork: "Tickets to process",
  start: "Start",
  end: "End",
  assignedAdvisor: "Assigned adviser",
  choose: "Choose",
  location: "Location",
  notes: "Notes",
  confirm: "Confirm",
  reject: "Reject",
  complete: "Complete",
  publicDma: "Public DMA requests",
  organization: "Organisation",
  close: "Close",
  employees: "employees",
  activeContacts: "Active contacts",
  downloadCalendar: "Download staff calendar (.ics)",
  liveDisconnected: "Live chat is not connected.",
  sendError: "The message could not be sent.",
  attachments: "Ticket attachments",
  attachmentsHelp:
    "All documents attached to this ticket by the client or the support team.",
  noAttachments: "No documents are attached to this ticket.",
  attachDocument: "Attach document",
  attachmentDownloadError: "The document could not be downloaded.",
  attachmentUploadError: "The document could not be uploaded.",
  assignment: "Assignment",
  noExpert: "No expert",
  assign: "Assign",
  begin: "Start",
  replyClient: "Public reply",
  send: "Send",
  internalNote: "Internal note",
  saveNote: "Save note",
  finalRecommendation: "Final recommendation",
  practicalRecommendation: "Practical recommendation",
  referralRecommendation: "Referral recommendation",
  resolveTicket: "Resolve ticket",
  overview: "Overview",
  organizations: "Organisations",
  subscriptions: "Subscriptions",
  contacts: "Contact requests",
  tickets: "Tickets",
  documents: "Documents",
  allTicketDocuments: "All ticket attachments",
  allTicketDocumentsHelp:
    "A central view of documents attached by clients and the support team.",
  noTicketDocuments: "No documents are attached",
  noTicketDocumentsHelp:
    "Documents will appear here as soon as they are attached to a ticket.",
  noContactRequests: "No contact requests",
  noContactRequestsHelp:
    "Requests submitted through the public contact form will appear here.",
  users: "Users",
  content: "Content",
  reports: "Reports",
  evidence: "Evidence documents",
  settings: "Settings",
  audit: "Audit records",
  activeSubscriptions: "Active subscriptions",
  expiredCancelled: "expired/cancelled",
  aiActRequests: "AI Act requests",
  publicInstitutions: "public institutions",
  members: "Members",
  approve: "Approve",
  suspend: "Suspend",
  reactivate: "Reactivate",
  renewSubscription: "Renew subscription",
  newInvitation: "New invitation",
  user: "User",
  sendInvitation: "Send invitation",
  reference: "Reference",
  note: "Note",
  activate: "Activate",
  confirmOfflinePayment: "Confirm offline payment",
  pendingPaymentInstruction:
    "These clients are waiting for confirmation. Enter the payment reference and select Activate.",
  paymentSettings: "Payment instructions",
  paymentSettingsHelp:
    "Enter only DigitMak's official bank details. Clients with Pending payment status will see this information.",
  paymentRecipient: "Recipient",
  paymentBank: "Bank",
  paymentAccount: "Bank account",
  paymentAmount: "Amount",
  paymentCurrency: "Currency",
  paymentPurpose: "Payment purpose",
  paymentReferenceGuide: "Payment reference instructions",
  paymentSupportEmail: "Payment support email",
  savePaymentSettings: "Save payment instructions",
  cancel: "Cancel",
  validUntil: "Valid until",
  handled: "Mark as handled",
  inviteRegistration: "Invite to register",
  emailReply: "Email reply",
  adminTicketOverview: "Administrator ticket overview",
  usersRoles: "Users and roles",
  addRole: "Add role",
  deactivate: "Deactivate",
  service: "Service",
  publicPage: "Public page",
  aiHelpSubscriptions: "AI Help Desk subscriptions",
  confirmedMeetings: "Confirmed meetings",
  referrals: "Referral recommendations",
  detailedReports: "Detailed PDF reports",
  contactsBreakdown: "Contacts",
  ticketsBreakdown: "Tickets",
  meetingsBreakdown: "Meetings",
  referralsBreakdown: "Referrals",
  exportData: "Report exports",
  downloadExcel: "Download Excel",
  downloadCsv: "Download CSV",
  groupBy: "grouped by",
  newEvidence: "New evidence record",
  relatedType: "Related type",
  relatedId: "Related ID",
  kpiCategory: "KPI category",
  period: "Period",
  template: "Template",
  file: "File",
  uploadEvidence: "Upload evidence",
  evidenceRegister: "Evidence document register",
  download: "Download",
  preview: "Preview",
  previewBlocked:
    "The preview was blocked by the browser. Allow pop-ups or download the document.",
  templateRegister: "Evidence templates",
  downloadBlank: "Download Excel template",
  selectTemplate: "Select template",
  chooseEvidenceFile: "Choose an evidence file.",
  evidenceDownloadError: "The evidence file could not be downloaded.",
  reportDownloadError: "The report could not be downloaded.",
  systemSetting: "System setting",
  key: "Key",
  value: "Value",
  description: "Description",
  save: "Save",
  systemActivities: "Append-only system activities",
  status: "Status",
  category: "Category",
  title: "Title",
  slug: "Slug",
  created: "Created",
  emailVerified: "Email verified",
  staffArea: "Staff workspace",
  onlineLink: "Online link",
  helpDeskAgent: "Help-desk agent",
  expert: "Expert",
  clientOrganization: "CLIENT ORGANISATION",
  dmaContactRequest: "DMA CONTACT REQUEST",
  primaryContact: "primary contact",
  dmaCategory: "Internal DMA category",
};

const sq: Copy = {
  ...en,
  actionError: "Veprimi dështoi.",
  loadOrganizationError: "Organizata nuk mund të ngarkohej.",
  decisionError: "Vendimi nuk mund të ruhej.",
  noStaffAccess: "Nuk keni qasje si staf.",
  noAdminAccess: "Nuk keni qasje administratori.",
  back: "Kthehu",
  details: "Detajet",
  triage: "Tiketat e klientëve",
  calendarMeetings: "Kalendari dhe takimet",
  contactRequests: "Kërkesat e kontaktit",
  clientPortal: "Portali i klientit",
  administration: "Administrimi",
  workspace: "Hapësira e punës",
  staffWorkspace: "HAPËSIRA E STAFIT",
  administrator: "Administrator",
  adminCenter: "QENDRA E KONTROLLIT ADMIN",
  new: "Të reja",
  inProgress: "Në proces",
  urgent: "Urgjente",
  ticketsForWork: "Tiketa për përpunim",
  start: "Fillimi",
  end: "Fundi",
  assignedAdvisor: "Këshilltari i caktuar",
  choose: "Zgjidh",
  location: "Vendndodhja",
  notes: "Shënime",
  confirm: "Konfirmo",
  reject: "Refuzo",
  complete: "Përfundo",
  publicDma: "Kërkesa publike DMA",
  organization: "Organizata",
  close: "Mbyll",
  employees: "punonjës",
  activeContacts: "Kontakte aktive",
  downloadCalendar: "Shkarko kalendarin e stafit (.ics)",
  liveDisconnected: "Biseda live nuk është e lidhur.",
  sendError: "Mesazhi nuk mund të dërgohej.",
  attachments: "Dokumentet e tiketës",
  attachmentsHelp:
    "Të gjitha dokumentet e ngarkuara në këtë tiketë nga klienti ose ekipi.",
  noAttachments: "Nuk ka dokumente të ngarkuara në këtë tiketë.",
  attachDocument: "Ngarko dokument",
  attachmentDownloadError: "Dokumenti nuk mund të shkarkohej.",
  attachmentUploadError: "Dokumenti nuk mund të ngarkohej.",
  assignment: "Caktimi",
  noExpert: "Pa ekspert",
  assign: "Cakto",
  begin: "Fillo",
  replyClient: "Përgjigje publike",
  send: "Dërgo",
  internalNote: "Shënim i brendshëm",
  saveNote: "Ruaj shënimin",
  finalRecommendation: "Rekomandimi përfundimtar",
  practicalRecommendation: "Rekomandim praktik",
  referralRecommendation: "Rekomandim referimi",
  resolveTicket: "Zgjidh tiketën",
  overview: "Përmbledhje",
  organizations: "Organizatat",
  subscriptions: "Abonimet",
  contacts: "Kërkesat e kontaktit",
  tickets: "Tiketat",
  documents: "Dokumentet",
  allTicketDocuments: "Të gjitha dokumentet e tiketave",
  allTicketDocumentsHelp:
    "Pamje qendrore e dokumenteve të ngarkuara nga klientët dhe ekipi i mbështetjes.",
  noTicketDocuments: "Nuk ka dokumente të ngarkuara",
  noTicketDocumentsHelp:
    "Dokumentet do të shfaqen këtu sapo të ngarkohen në një tiketë.",
  noContactRequests: "Nuk ka kërkesa kontakti",
  noContactRequestsHelp:
    "Kërkesat e dërguara përmes formularit publik do të shfaqen këtu.",
  users: "Përdoruesit",
  content: "Përmbajtja",
  reports: "Raportet",
  evidence: "Dokumentet dëshmuese",
  settings: "Cilësimet",
  audit: "Regjistrat e auditimit",
  activeSubscriptions: "Abonime aktive",
  expiredCancelled: "të skaduara/anuluara",
  aiActRequests: "kërkesa AI Act",
  publicInstitutions: "institucione publike",
  members: "Anëtarët",
  approve: "Mirato",
  suspend: "Pezullo",
  reactivate: "Riaktivizo",
  renewSubscription: "Rinovo abonimin",
  newInvitation: "Ftesë e re",
  user: "Përdoruesi",
  sendInvitation: "Dërgo ftesën",
  reference: "Referenca",
  note: "Shënim",
  activate: "Aktivizo",
  confirmOfflinePayment: "Konfirmo pagesën jashtë linje",
  pendingPaymentInstruction:
    "Këta klientë presin konfirmim. Vendosni referencën e pagesës dhe zgjidhni Aktivizo.",
  paymentSettings: "Udhëzimet e pagesës",
  paymentSettingsHelp:
    "Vendosni vetëm të dhënat zyrtare bankare të DigitMak. Klientët në pritje të pagesës do t'i shohin këto informacione.",
  paymentRecipient: "Përfituesi",
  paymentBank: "Banka",
  paymentAccount: "Llogaria bankare",
  paymentAmount: "Shuma",
  paymentCurrency: "Valuta",
  paymentPurpose: "Qëllimi i pagesës",
  paymentReferenceGuide: "Udhëzimi për referencën e pagesës",
  paymentSupportEmail: "Email për ndihmë me pagesën",
  savePaymentSettings: "Ruaj udhëzimet e pagesës",
  cancel: "Anulo",
  validUntil: "Vlen deri më",
  handled: "Shëno si e përpunuar",
  inviteRegistration: "Fto për regjistrim",
  emailReply: "Përgjigje me email",
  adminTicketOverview: "Përmbledhja administrative e tiketave",
  usersRoles: "Përdoruesit dhe rolet",
  addRole: "Shto rol",
  deactivate: "Çaktivizo",
  service: "Shërbim",
  publicPage: "Faqe publike",
  aiHelpSubscriptions: "Abonime AI Help Desk",
  confirmedMeetings: "Takime të konfirmuara",
  referrals: "Rekomandime referimi",
  detailedReports: "Raporte të detajuara",
  contactsBreakdown: "Kontaktet",
  ticketsBreakdown: "Tiketat",
  meetingsBreakdown: "Takimet",
  referralsBreakdown: "Referimet",
  exportData: "Eksporti i raporteve",
  downloadExcel: "Shkarko Excel",
  downloadCsv: "Shkarko CSV",
  groupBy: "grupuar sipas",
  newEvidence: "Dosje e re dëshmuese",
  relatedType: "Lloji i lidhur",
  relatedId: "ID e lidhur",
  kpiCategory: "Kategoria KPI",
  period: "Periudha",
  template: "Modeli",
  file: "Skedari",
  uploadEvidence: "Ngarko dëshminë",
  evidenceRegister: "Regjistri i dokumenteve dëshmuese",
  download: "Shkarko",
  preview: "Shiko",
  previewBlocked:
    "Shikimi u bllokua nga shfletuesi. Lejoni pop-up ose shkarkoni dokumentin.",
  templateRegister: "Modelet e dëshmive",
  downloadBlank: "Shkarko modelin Excel",
  selectTemplate: "Zgjidh model",
  chooseEvidenceFile: "Zgjidhni një skedar dëshmues.",
  evidenceDownloadError: "Skedari dëshmues nuk mund të shkarkohej.",
  reportDownloadError: "Raporti nuk mund të shkarkohej.",
  systemSetting: "Cilësim i sistemit",
  key: "Çelësi",
  value: "Vlera",
  description: "Përshkrimi",
  save: "Ruaj",
  systemActivities: "Aktivitete të pandryshueshme të sistemit",
  status: "Statusi",
  category: "Kategoria",
  title: "Titulli",
  slug: "Shenja URL",
  created: "Krijuar",
  emailVerified: "Email-i u verifikua",
  staffArea: "Hapësira e punës së stafit",
  onlineLink: "Lidhja online",
  helpDeskAgent: "Këshilltar i help-desk",
  expert: "Ekspert",
  clientOrganization: "ORGANIZATA KLIENTE",
  dmaContactRequest: "KËRKESË KONTAKTI DMA",
  primaryContact: "kontakt kryesor",
  dmaCategory: "Kategoria e brendshme DMA",
};

export const workspaceCopy = (language: Language): Copy =>
  language === "en" ? en : language === "sq" ? sq : mk;
